server.port=8084
spring.application.name=catalogo

# MongoDB config
spring.data.mongodb.uri=mongodb://${MONGO_USER:mongo}:${MONGO_PASSWORD:mongo}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/catalogo_db?authSource=admin
